### ISSUE TITLE
Double access-control-allow-origin header 

### ISSUE THREAD

**Issue by riccardogiambra** [bjerkio/oidc-react#1001]
I'm having this issue with cors header:
``
Access to fetch at 'https://<MY-OIDC-PROVIDER>/.well-known/openid-configuration' from origin 'http://localhost:3002' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
``
Looking at network tab I saw this:
![tempsnip](https://user-images.githubusercontent.com/100277759/235257553-18425f95-44f7-4894-a91f-cb82c622990b.png)
the access-control-allow-origin header was added twice.
i'm doing a simple react app and MY-OIDC-PROVIDER is a self hosted instance of authelia and I use Nginx Proxy Manager as reverse proxy.

EDIT:
i forgot that my nginx proxy manager must had that header, is it possible to disable the one added by the oidc-react?

**Comment by riccardogiambra** [comment]
My bad, while I was writing it is popped on my mind to check nginx config and i add the second header there. It could be usefull by the way having the possibility to disable the adding of this header by oidc-react

**Comment by simenandre** [comment]
Not sure how I can help you with this. If I were you, I would look deeper into how [`oidc-client-ts`](https://github.com/authts/oidc-client-ts) works.

Also, not sure if it's even `oidc-react` or `oidc-client-ts` that adds these headers, it seems weird to me.

**Comment by simenandre** [comment]
I'm closing this as stale, let me know how we can help further!
