### ISSUE TITLE
Avoiding "No authority or metadataUrl configured" when authentication isn't needed?

### ISSUE THREAD

**Issue by lupuchard** [bjerkio/oidc-react#1011]
My app only requires authentication in certain contexts, but if oidc configuration is omitted from the AuthProvider, I get the error "No authority or metadataUrl configured on settings". I can't conditionally render AuthProvider because it's required for useAuth() and react doesn't allow the conditional use of hooks.

Is there any way to omit authentication in the AuthProvider without getting this error?

**Comment by simenandre** [comment]
Closing this as stale. Please open a new issue or let me know you still have this issue in a comment 👍

**Comment by tuwid** [comment]
it is still an issue
