### ISSUE TITLE
Uncaught (in promise) Error: No matching state found in storage     at OidcClient.readSigninResponseState (oidc-client-ts.js:1785:1)     at async UserManager.signinCallback

### ISSUE THREAD

**Issue by curiosDevInSearch** [bjerkio/oidc-react#1015]
![image](https://github.com/bjerkio/oidc-react/assets/137162934/2d5a0c47-954c-4fad-8df6-7fa448bb6437)

Uncaught (in promise) Error: No matching state found in storage     at OidcClient.readSigninResponseState (oidc-client-ts.js:1785:1)     at async UserManager.signinCallback

After I signed in and redirected back to my app I am getting that console error, need help to fix it

**Comment by Sandbox-Freddy** [comment]
I got the same issue

**Comment by Sandbox-Freddy** [comment]
I got the same error after sign in

**Comment by Ploppz** [comment]
I see that there are similar issues in the past but these have been marked as fixed.
I'm also experiencing this issue using version 3.2.2. Our IdP is Azure.

**Comment by laughingwhale1** [comment]
Any update? @Ploppz did you solve the issue?

**Comment by Ploppz** [comment]
Well I started using `oidc-client-ts` but ... I'm still experiencing a "Error: No state in response" error, so maybe I'm just doing something wrong. In my case, the error doesn't seem to affect the application though.

**Comment by laughingwhale1** [comment]
Your error may mean the response code doesn't contain state= query param.

**Comment by OlegTar** [comment]
According to the source code there should be the SignInError handler. But it's absent when you install the npm package.

**Comment by simenandre** [comment]
I am closing this for now; please let me know if the issue continues and if there is anything we can do. I assume this issue is no longer since the issue has been stale for a good while and that `SignInError` has now been released.

I could be wrong, so please let me know!
