### ISSUE TITLE
I had redirect to the login page and after i login it, it shows userData null so i can't get the user's data. Can someone help me?

### ISSUE THREAD

**Issue by MaggieCohans** [bjerkio/oidc-react#1051]
![image](https://github.com/bjerkio/oidc-react/assets/103938534/74b11844-ba90-490b-8016-efa18c700fb0)

**Comment by simenandre** [comment]
Thank you for opening this issue! I am closing this as stale since it hasn't been updated for a while. Please open a new issue or let me know you still have this issue in a comment 👍
