### ISSUE TITLE
onSignInError prop does not exist in version 3.2.2

### ISSUE THREAD

**Issue by djwillcaine** [bjerkio/oidc-react#1063]
I'm building an app that requires some error handling when authentication fails because of a network request error when contacting the authority. I see that there is an onSignInError prop that exists for the AuthProvider in the docs and the source code that I think will work. However, this is not included in the most recent release, 3.2.2.

**Comment by simenandre** [comment]
Oh, that is interesting! I am not sure what happened here, let me have a look!

**Comment by simenandre** [comment]
So, the reason this happened was just that it wasn't released. Now it is!

https://github.com/bjerkio/oidc-react/releases/tag/v3.3.0

Let me know how it went, if you still have issues, let me know. I'll close this issue in a while if I don't hear back :)

**Comment by simenandre** [comment]
Closing this for now, @djwillcaine. Let me know if you still have issues. Thanks for letting me know :)
