### ISSUE TITLE
Feature request: Add a withAuth function similar to withRouter

### ISSUE THREAD

**Issue by hmvp** [bjerkio/oidc-react#13]
See https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/withRouter.md and https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/withRouter.js

For all the people who are using class based components

Possible implementation based on https://github.com/pbeshai/use-query-params/blob/master/src/withQueryParams.tsx
```typescript
type Diff<T, K> = Omit<T, keyof K>;

/**
 * A public higher-order component to access the imperative API
 */
function withAuth<P extends AuthContextProps>(Component: React.ComponentType<P>) {
    const displayName = `withAuth(${Component.displayName || Component.name})`;
    const C: React.FC<Diff<P, AuthContextProps>> = props => {
        const auth = useAuth();

        return (
            <AuthContext.Consumer>
                {context => {
                    return <Component {...(props as P)} {...auth} />;
                }}
            </AuthContext.Consumer>
        );
    };

    C.displayName = displayName;

    return C;
}
```

**Comment by cobraz** [comment]
Thanks for your issue!

In my opinion, it makes sense to add it. Looking at your example, you wouldn't need both `<AuthContext.Consumer />` and `useAuth()`. Maybe you want to open a PR?

**Comment by hmvp** [comment]
You are right. Added a pr
