### ISSUE TITLE
Re-export oidc-client's User type

### ISSUE THREAD

**Issue by ryancole** [bjerkio/oidc-react#185]
Can we adjust the code so that the oidc-react package re-exports the `User` type from oidc-client-js? It'd be helpful for function parameter typing. Thanks.

**Comment by cobraz** [comment]
Hi! Thanks for opening an issue!

So you can't just import directly from `oidc-client-js`? Can you describe the use-case further?

**Comment by ryancole** [comment]
I suppose I could import that way, but oidc-client is not an explicit
dependency and so feels a bit weird importing from something I didn’t
install.

Use case is just to apply type definition to some of the callbacks from
oidc-react, such as onSignIn etc.

**Comment by cobraz** [comment]
Ahh, make sense. Maybe we should export all exports from `oidc-client-js` to serve yours and others use-cases, should only be one line in `index.ts` 

Like so, I believe:

```
export * from './AuthContext';
export * from './useAuth';
export * from './withAuth';
export * from 'oidc-client-js';
```

Would you like to submit a pull request on this?

**Comment by ryancole** [comment]
Can do. I’ll send one in later this evening.

**Comment by cobraz** [comment]
Thanks 🙏
