### ISSUE TITLE
Idp SignOut

### ISSUE THREAD

**Issue by johnkors** [bjerkio/oidc-react#20]
Hi,

`oidc-js` calls the `endsession` endpoint on logout, so the user get's not only logged out at the client, but also the identityprovider. The logout in `oidc-react` only logs out at the client (removes auth data from session storage).

I could not find a way of doing the full signout at the identityprovider - is there one? Or could you add it? The `UserManager. signoutRedirect()` in `oidc-js` will execute the idp signout redirect, I believe. 

[ref Angular sample](https://github.com/IdentityModel/oidc-client-js/blob/dev/samples/Angular/App/src/app/core/services/auth.service.ts#L41)

**Comment by cobraz** [comment]
Hello,

Thanks for the issue! This is a feature we really need – you are right! Maybe you want to propose a pull request?

**Comment by cobraz** [comment]
This has been solved with the great help of @lclc98 in #48. I'm going to publish this very soon!

**Comment by johnkors** [comment]
Nice! Thanks for the heads up :) And thanks to @lclc98 for the implementation 👏
