### ISSUE TITLE
Can not use signinSIlent Method with this package

### ISSUE THREAD

**Issue by freyonism** [bjerkio/oidc-react#248]
As I saw and tried, this package only supports signRedirect. Here: 
https://github.com/bjerkio/oidc-react/blob/26fb9c922425471716befabca29414fb7a113460/src/AuthContext.tsx#L88

Because of this effect, I can not use signinSilent and querySessionStatus which depends on it. It will throw frame window timeout.  But, when I tried to call `signinSilentCallback` on callback page, it always thowrs no matching state found, because `getUser` always run first before the `signinSilentCallback`.  

Changing the `signinRedirectCallback` to `signinCallback` will fix the issue  as this method can decide which sign in method is used.
https://github.com/IdentityModel/oidc-client-js/blob/fe2d2865ebf638a4224d1d3ac8102eb5c006dd01/src/UserManager.js#L288

**Comment by cobraz** [comment]
Hi! 👋

Thanks for opening this issue, and thanks for pointing this out! Maybe you can open a pull request to fix this?
