### ISSUE TITLE
Page Reload Issue

### ISSUE THREAD

**Issue by jspizziri** [bjerkio/oidc-react#28]
Hey, just installed this package, and I'm having an issue where the page is refreshed, the user object doesn't seem to be getting fetched from the session.

Effectively doing something like the following and on page refresh, `userData` doesn't seem to be getting set (or at least triggering a rerender).

Thanks in advance.

```ts
import React from 'react';

import { useAuth } from 'oidc-react';

export const AuthButton: React.FC = () => {
  const auth = useAuth();

  if (!auth.userData) {
    return (
      <button onClick={() => auth.signIn()}>log in</button>
    );
  }

  return (
    <button onClick={() => auth.signOut()}>log out</button>
  );
}
```

**Comment by jspizziri** [comment]
Additional context, this is specifically when `autoSignIn={false}`.

**Comment by cobraz** [comment]
Hello,

Thank you for the issue! You have covered you app with `<AuthProvider>`?

Let me test this out on my test repository.

**Comment by jspizziri** [comment]
@cobraz , I have the `AuthProvider` wrapped around my `Router` in my `App.tsx`, so it should definitely be available in the component that I'm calling it in, although I have some other providers (like the `ApolloProvider`) on a higher level.

**Comment by jspizziri** [comment]
@cobraz any progress on this? Just upgraded to `alpha.5` and the problem persists.

**Comment by cobraz** [comment]
Can you provide an example repository? It would help a lot!

**Comment by jspizziri** [comment]
Hey, I ended up switching to `react-oidc`, thanks again!
