### ISSUE TITLE
Please help, my app isn't being called back after signOut because of AuthContext

### ISSUE THREAD

**Issue by kodeschooler** [bjerkio/oidc-react#327]
Hi, I've never made a request here so please forgive me if this is not the correct way to submit an issue or ask for help. I have a new job that is requiring me to include oauth/identity functionality on a new react app (which I'm trying to learn also). I've decided to use your library since it looked straightforward for my needs. After several days of working with it, I realized today that my post_logout_redirect_uri setting is being ignored. I tracked it down after I looked at the code in your AuthContext.tsx file-in particular when it instantiates a UserManager, using the following code:

```typescript
export const initUserManager = (props: AuthProviderProps): UserManager => {
  if (props.userManager) return props.userManager;
  const {
    authority,
    clientId,
    clientSecret,
    redirectUri,
    responseType,
    scope,
    automaticSilentRenew,
  } = props;
  return new UserManager({
    authority,
    client_id: clientId,
    client_secret: clientSecret,
    redirect_uri: redirectUri,
    silent_redirect_uri: redirectUri,
    post_logout_redirect_uri: redirectUri,
    response_type: responseType || 'code',
    scope: scope || 'openid',
    loadUserInfo: true,
    automaticSilentRenew,
  });
};
```

It only accepts authority,
    clientId,
    clientSecret,
    redirectUri,
    responseType,
    scope,
    automaticSilentRenew

Is there a good reason for this, because the userManager settings object is supposed to take many more params, including the post logout redirect uri. Is this designed on purpose to have the redirect_uri and post_logout_redirect_ui always be the same endpoint?

Or maybe I just don't understand, maybe there's a simple workaround so my app works with this lib. The useAuth hook is all over my components so I'm eager to see if this can be fixed. 

Maybe there's a perfectly reasonable answer to it (hopefully). And if so I will be grateful for direction.

Thank you for any input or advice.

Thanks

**Comment by cobraz** [comment]
Hello 👋

Sorry for the late reply, I've been a hasty week. We are passing arguments directly to the underlying package, oidc-client. You can read about the arguments here; https://github.com/IdentityModel/oidc-client-js/wiki

In other words, we can support all the same arguments as `UserManager`. After looking at our implementation from your perspective, I realize that could do a better job with the `initUserManager`. For now, you are welcome to create a pull request where you add `post_logout_redirect_uri` to our props. I'm going to have a chat with @ryancole, we'll probably create a separate issue to track general improvements too :)

**Comment by cobraz** [comment]
I forgot to add, you can provide your own UserManager as well. That might suit your use-case in the short term!

**Comment by kodeschooler** [comment]
Hey, thank you for the feedback! I haven't done a PR before so I'll just read up on it a bit and then do it later or tonight. 

Re- the short-term fix: are you saying to instantiate my own UM in my App with the desired UM props, and then simply pass that UM to the AuthProvider? Then everything should work as normal, correct? I think that's what you're saying, but I just want to be sure. Thanks 

Ps- other than this it's been terrific and easy to use!

**Comment by cobraz** [comment]
Yes, you can provide your own UserManager. 😉

Example:
```jsx
const userManager = new UserManager({
	// ...
})
// ...
<AuthProvider userManager={userManager}>
	...
</AuthProvider>
```

**Comment by cobraz** [comment]
I'm closing this now, let me know if you have any further questions :)

**Comment by kodeschooler** [comment]
Yes, thank you. I have it working now using my own created UM.

**Comment by kodeschooler** [comment]
I'm not sure if this is the place to ask, but can you tell me if your library is set up to automatically renew a token if it expires? I set the flag automaticSilentRenew to true when passing AuthProviderProps. My session was still alive after leaving my app open all night (my tokens currently expire in one hour). When I came back I tried loading a component that calls my api and it returned with a 401 unauthorized. Then I F5 refreshed and it got a new token and was successful. Do you know how we control this? For example, anytime a token is expired, go get a new one so we never get a 401 and have a call fail? I see there are events on UM for tokens about to expire, etc. So I guess my question is, does automaticSilentRenew require any logic to be written to avoid what I described above? Thank you again!
