### ISSUE TITLE
Add export for WebStorageStateStore from oidc-client

### ISSUE THREAD

**Issue by ryancole** [bjerkio/oidc-react#344]
Makes sense to re-export this for users who need access to it.

**Comment by Powersource** [comment]
Maybe export the entire oidc-client default export? I'm finding myself also importing that to be able to do

```js
Oidc.Log.logger = console;
Oidc.Log.level = Oidc.Log.DEBUG;
```

**Comment by cobraz** [comment]
@Powersource or @ryancole, is this something either of you could open a quick PR on? I think it makes sense to do this even though we have #652.

**Comment by cobraz** [comment]
Closing this as it's stale.
