### ISSUE TITLE
[Feature Request] Cannot set authorize endpoint state param

### ISSUE THREAD

**Issue by johnkors** [bjerkio/oidc-react#36]
Hi, 

I see there's a `onBeforeSignin` function to use for storing data before signing in. In the OIDC standard there's already something for this - the `state` parameter. RPs set this on requests towards the authorize endpoint. 

In `oidc.js`, [this is done via :
`mgr.signinRedirect({state:'some data'})`](https://github.com/IdentityModel/oidc-client-js/blob/dev/samples/VanillaJS/public/identityserver-sample.js#L108), where `some data` can be anything you put into it, url-encoded.

[The `signIn` function of the authContext](https://github.com/bjerkio/oidc-react/blob/alpha/src/AuthContext.tsx#L113) hides this API, though. Could you make the signIn function take an object that can be passed to the `signinRedirect` method of oidc.js?

**Comment by cobraz** [comment]
Great idea! Absolutely, we'll add that in. 👍
