### ISSUE TITLE
Silent token refresh doesn't seem to actually update the token

### ISSUE THREAD

**Issue by Powersource** [bjerkio/oidc-react#361]
So I've been doing a bunch of debugging. In my app it currently looks like:

1. The access token is e.g. "tokenabcd"
2. The user can do actions that require authentication.
3. The access token is refreshed (supposedly) successfully according to logging.
4. The token is still "tokenabcd"
5. The user can sometimes still do actions that require authentication, but after a bit my backend (just checking that the jwt isn't expired and all that) starts complaining that the user isn't authenticated.
6. Refresh the page (f5), now you have a new token "tokendcba", and actions that require authentication work again.

**Comment by Powersource** [comment]
I thought (still relatively new to react) it might have been this line https://github.com/bjerkio/oidc-react/blob/71d86cfb195af942feb3d1add7f5ea71e31abe4e/src/AuthContext.tsx#L105 not containing all its dependencies (according to https://www.npmjs.com/package/eslint-plugin-react-hooks ) but filling it out with the rest didn't help.

**Comment by Powersource** [comment]
I think I might have found the problem! At the above step 3 the token is refreshed and put in storage (localstorage in my case, but I'm guessing that shouldn't matter here). userData from useAuth will still give you the old access token etc., but if you go into the browser debug tools and search in local(/session)storage and search for `oidc.user:` (it will be followed by a url) you should find a key that contains the new user data and new access token. You can verify this, since if you refresh the page then the access token that useAuth gives you will be the one that you found under `oidc.user:` and stuff will work again.

**Comment by cristian-eriomenco** [comment]
> I think I might have found the problem! At the above step 3 the token is refreshed and put in storage (localstorage in my case, but I'm guessing that shouldn't matter here). userData from useAuth will still give you the old access token etc., but if you go into the browser debug tools and search in local(/session)storage and search for `oidc.user:` (it will be followed by a url) you should find a key that contains the new user data and new access token. You can verify this, since if you refresh the page then the access token that useAuth gives you will be the one that you found under `oidc.user:` and stuff will work again.

Have you found a fix?

**Comment by Powersource** [comment]
Yep in the above PR (but you seem to have found that now :) )
