### ISSUE TITLE
how to get access_token along with id_token from azure ad

### ISSUE THREAD

**Issue by Hari-sankoju** [bjerkio/oidc-react#368]
Hi Team, I am trying to integrate my react app with Azure AD. I need both id_token and access_token from Azure response.
I found in documentation that to get access_token as well, we need to pass resource identifier in the OAuth request, so I am passing extraQueryParams{resource:"...."} but it seems oidc-react not passing it to oidc-client, please let me know how to pass extraQueryParams and how to get access_token

here is the sample what i am doing.
const oidcConfig = {
  authority: 'XXXXXXXXX',
  clientId:
    'XXXXXXXXXXXXXXX',
  responseType: 'id_token token',
  redirectUri:'XXXXXXXXXXXXXX',
  scope: 'openid',
  extraQueryParams: {resource:'XXXXXXXXXXXXXXXXXXXXX'}
};

<AuthProvider {...oidcConfig} onSignIn={this.checkLogin}>

**Comment by Powersource** [comment]
It doesn't look like `extraQueryParams` is actually passed along by oidc-react https://github.com/bjerkio/oidc-react/blob/master/src/AuthContext.tsx#L37-L45

I think you might have to do like me here https://github.com/Edgeryders-Participio/realities/blob/master/ui/src/App/App.js#L53 and create your own UserManager that you then pass along.

**Comment by cobraz** [comment]
Thank you for using `oidc-react`!

As @Powersource states, you can use a custom `UserManager` for this. I'll be closing this for now, let me know if there is anything else we can help with 🎉
