### ISSUE TITLE
awkward loop after login

### ISSUE THREAD

**Issue by noobadmin** [bjerkio/oidc-react#385]
Hi! Nice library, I was following your examples starting with minimal config:
```
  const oidcConfig = {
    authority:
      'http://keycloak:8080/auth/realms/master/.well-known/openid-configuration',
    clientId: 'account',
    redirectUri: 'http://localhost:3000/',
  }
```
Works out of the box, however I'm running into a weird loop: https://imgur.com/a/9YfS50B It eventualy stops after about ten of those and works fine from then on. It's not usable in this state though.

Authenticating against roughly default keycloak instance.

I'm quite sure, I didn't include any obvious :poop: code while implementing this, however I lack skills to further debug what's causing this :(

source https://github.com/panosc-portal/frontend/blob/oidc-generic/src/App/app.js

**Comment by noobadmin** [comment]
`onSignIn: () => (window.location.hash = '')` doesn't seem to help...

**Comment by noobadmin** [comment]
OK, IdentityModel/oidc-client-js's userManager has the same behaviour. Frustrating...

**Comment by ctron** [comment]
I am just running into the same issue. Is there a workaround?

**Comment by cobraz** [comment]
AFAIK, no. I would love to look closer at this, as I know more than you guys are having issues with it (including a colleague of mine).

Maybe you wanna take a stab at it? At least determine why it's happening, so we can see where we can fix it 🤷‍♂️

**Comment by ctron** [comment]
I am not sure I can help. Beeing a JavaScript and React noob :grin: 

I ended up switching to https://github.com/AxaGuilDEv/react-oidc … which doesn't seem to show this behavior.
