### ISSUE TITLE
Silent renew doesn't work if window is not focused. 

### ISSUE THREAD

**Issue by SaimirKapaj** [bjerkio/oidc-react#416]
Hello! First of all, thank you for this great library. The best react oidc-client I could find so far. 

Regarding the issue, the automaticSilentRenew doesn't work if the window is not focused. So, if you are in a different tab and you try to switch back to the tab of the application after the token is expired, the automaticSilentRenew doesn't work anymore. 

It should be great to trigger the automaticSilentRenew on windows focus if the token is not valid anymore.

**Comment by cobraz** [comment]
Hello,

Thank you for so much for those kind words! I'm unfamiliar with the issue you're having, but I'd like to point out that [oidc-client-js](https://github.com/IdentityModel/oidc-client-js/issues/1206) has multiple references on how you can do this.

I would like to tag @ryancole in on this, as he has contributed code on this package in relation with `automaticSilentRenew`.

Again, thank you for using it!

**Comment by MomaniNidal** [comment]
could you help me how refresh the token using your plugin how I can create an event or method for that , also I use useAuth method but also userdata and usermanger is null

**Comment by MomaniNidal** [comment]
I need to define a user manager or not

**Comment by cobraz** [comment]
@MomaniNidal this should be handled by [oidc-client](https://github.com/IdentityModel/oidc-client-js). You should be able to find some details on that on their issue tracker.

Thanks for reporting, I'll close this for now. If there is any further questions, let me know. 💯
