### ISSUE TITLE
Unprotected 404 route?

### ISSUE THREAD

**Issue by matthoskins1980** [bjerkio/oidc-react#434]
I'm currently implementing a solution that has protected and unprotected routes. That part is working great. I'm trying to implement a catch all 404 page. I'm having difficulty figuring out where to place this. If I place it after the protected routes component, the 404 page gets redirected to my SSO provider.

Is there a way to implement 404 AND have it unprotected?

**Comment by cobraz** [comment]
Hello @matthoskins1980!

Thank you for using `oidc-react`! Which router are you using? You should be able to handle this without the help of this library.

**Comment by wapenshaw** [comment]
```tsx
import { useAuth } from 'oidc-react';
import React from 'react';
import { Redirect, Route, RouteProps } from 'react-router-dom';

export interface ProtectedRouteProps extends RouteProps {
	redirectPath: string;
}

const ProtectedRoute: React.FunctionComponent<ProtectedRouteProps> = (props) => {
	const auth = useAuth();
	if (auth?.userData !== null) {
		return <Route {...props} component={props.component} render={undefined} />;
	} else {
		return <Redirect to={{ pathname: props.redirectPath }} />;
	}
};

export default ProtectedRoute;
```

@cobraz not him but I came here looking for help. this is a protected route component I wrote, however when checking for some reason the `auth.userData` is null always for this component. However, the same useAuth() call works in other components and I am able to retrieve data from authcontext without issue. Any suggestions on how to go about this?

**Comment by cobraz** [comment]
@wapenshaw would you mind setting up a minimal reproduction repo?

**Comment by cobraz** [comment]
Closing this now as it's become stale. Let me know if you're able to provide more information 👍
