### ISSUE TITLE
How can we remove some routes from the auth list?

### ISSUE THREAD

**Issue by okandonmez** [bjerkio/oidc-react#544]
Hi, 

I don't want some routes to be authorize. So, i tried something below but in that case 'onSignIn' function is not triggering.

```
import { AuthProvider } from 'oidc-react';

const oidcConfig = {
  onSignIn: () => {
    // Redirect?
  },
  authority: 'https://demoauth.dev/oauth',
  clientId: 'demo',
  redirectUri: 'http://localhost:3000/'
};

const Routes = () => (
    <Switch>
      <Route exact path="/">
        <Dashboard />
      </Route>
     <AuthProvider {...oidcConfig}>
     <Route exact path="/list-of-sth">
        <Dashboard />
      </Route>
      </AuthProvider>
    </Switch>
);
```

Could it be that such an error happened because the redirect-uri is not "localhost: 3000/list-of-sth".

**Comment by cobraz** [comment]
Hello, thank you for using `oidc-react`!

It is probably because, as you said, the redirect-uri is not `location:3000/list-of-sth`

**Comment by cobraz** [comment]
I'm gonna close this for now. If you have any further questions – let me know! Thanks for reporting 💯
