### ISSUE TITLE
Fix `typedoc`

### ISSUE THREAD

**Issue by cobraz** [bjerkio/oidc-react#551]
After upgrading to [>0.20.0](https://github.com/TypeStrong/typedoc/releases/tag/v0.20.0) `typedoc` has stopped working; and our documentation is outdated.

This issue is open for anyone who wants to help out! 🙏

**Comment by mancioshell** [comment]
Hi have modified typedoc.js to typedoc.json and removed legacy options:

```
{
  "readme": "none",
  "plugin": "typedoc-plugin-markdown",
  "out": "docs/",
  "exclude": ["node_modules/**"]
}
```
The changes has a strong impact on docs output. I have a pull request ready to solve this issue, but i would like to know if i have to add other options to typedoc.json.

Could you try in your local environment and give me a feedback?

**Comment by cobraz** [comment]
Thank you very much! You can post your pull request and we can look at the results? :)
