### ISSUE TITLE
add AuthState via reducer

### ISSUE THREAD

**Issue by pamapa** [bjerkio/oidc-react#583]
something like:
```
export interface AuthState {
  user?: User;
  isAuthenticated: boolean;
  isLoading: boolean;
  error?: Error;
}
```

inside the context:
```
const [state, dispatch] = useReducer(reducer, initialAuthState);
```

Additionally a AuthReducer.tsx file is handling the reducing. I could put together a merge request, iff wanted.

**Comment by cobraz** [comment]
Thanks for opening this issue, @pamapa. I'm closing this now, but we'll use this for reference in regards to #652.

For later reference, @pamapa have made a separate library that adds this. So, if you are looking for such functionality, have a look at: https://github.com/pamapa/react-oidc-context
