### ISSUE TITLE
Using web browser Refresh

### ISSUE THREAD

**Issue by martenssa** [bjerkio/oidc-react#596]
We have setup our application to use odic-react and everything works except for one thing.

When we have have signed in to the application and then presses the Refresh button we are 
redirected to our landing page for login.
On the landing page we have concluded:
- We can see that the session storage still contains the oidc information 
- We can use auth.userManager.getData() and retrieve the user 
- auth.userData is null

Because of this, that auth.userData is null, our application assumes that the user is not authenticated. 

Can we do anything to force reload of the userdata from the session storage?
Is there any other way of solving this problem?
We could of course make a new sign in, by doing auth.userManager.signinRedirect(), 
but it would be nicer to get the information from the session storage and save time.

**Comment by pseudoramble** [comment]
I'm not a maintainer here, just a user. That being said, I have a similar setup and have no issue with refreshing pages, and it's been working for a while (including at least up until 1.5.0). 

A few ideas I can think to confirm:

1. On the pages you're being redirected from, confirm that the `AuthProvider` is setup and that `useAuth` or `withAuth` is connected to the component. That way you can confirm that `userData` is set there.
2. Are you getting a signin callback style error? I've had those in the past where I was not properly calling the signinRedirectCallback and causing issues for logins.

**Comment by martenssa** [comment]
I realize that I haven't been 100% clear in my writing.
Our application is single page application, so when I say redirected to page I actually mean routed to path.

Yes, I think everything is correct setup up with the AuthProvider as we are able to use useAuth after we have pressed refresh.

We don't get any signin callback errors and we are not expecting any as we want to avoid making a new signin when pressing refresh. Instead we hope to use the already existing information in the session storage.

**Comment by martenssa** [comment]
It seems that we managed to solve the problem by adding some extra code in our AuthRoute,
Main change is that we now also use isLoading as part of our logic.

```
export const AuthRoute = (props) => {
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [isLoadingUser, setIsLoadingUser] = useState(true);
  const auth = useAuth();

  useEffect(() => {
    const loadUser = async () => {
      try {
        setIsLoadingUser(auth && auth.isLoading);
        setIsAuthenticated(auth && !auth.isLoading && auth.userData && !auth.userData.expired);
      } catch (err) {
        setIsAuthenticated(false);
        console.log(err);
      } finally {
      }
    };
    loadUser();
  }, [auth]);

  if (isLoadingUser) {
    return <h1>Loading user...</h1>;
  } else {
    if (!isAuthenticated) {
      return <Redirect to="login"></Redirect>;
    } else {
      return <Route {...props}></Route>;
    }
  }
};

```

**Comment by cobraz** [comment]
Sounds great! I'll close this for now :) 🎉
