### ISSUE TITLE
checksession called too many times

### ISSUE THREAD

**Issue by lijianyu1985** [bjerkio/oidc-react#612]
I found that the checksession api be called too many times, and found that there are too many UserManager be created, cache userManager in window and avoid the issue

![image](https://user-images.githubusercontent.com/1027001/116513936-4b7e5d00-a898-11eb-9a8a-82b80305023b.png)

**Comment by arie-azhari** [comment]
i have fork and add props checkSessionInterval
https://github.com/arie-azhari/oidc-react

**Comment by cobraz** [comment]
We should probably use useEffect or something like that. I haven't been able to reproduce this issue. 

@arie-azhari you can use your own UserManager to set `checkSessionInterval`. Let me create an example for you:

```typescript
import React from 'react';
import { UserManager, AuthProvider } from 'oidc-react';

const userManager = new UserManager({
 // ... set your config here
});

export const HelloComponent: React.FC = () => (
	<AuthProvider userManager={userManager}>
	{/* ... */}
	</AuthProvider>
);
```
