### ISSUE TITLE
access_token is undefined

### ISSUE THREAD

**Issue by enriquemorenotent** [bjerkio/oidc-react#668]
For some reason, after I log in with my Auth Provider, I get back a id_token, but not an access token.

![image](https://user-images.githubusercontent.com/368842/125869411-0ae3efa3-5957-4104-8c5e-e894275d2bed.png)

I have seen my colleagues being able to make requests to the Resources Provider using the id_token, but as I had understood, that is not what should be done. It should be the access_token, right?

This is my component:

```jsx
const Application: React.FunctionComponent<{}> = () => {
  return (
    <AuthProvider
      authority="..."
      clientId="..."
      redirectUri="..."
      scope="openid profile email"
      responseType="code"
    >
      <MainLayout></MainLayout>
    </AuthProvider>
  );
};
```

What am I doing wrong??

**Comment by cobraz** [comment]
You can choose what kind of token you receive from your OIDC server. Which flow are you using at the moment?
