### ISSUE TITLE
How to sign in from a component outside of the AuthProvider

### ISSUE THREAD

**Issue by eTallang** [bjerkio/oidc-react#691]
Hi! 
This is probably a very simple question, but I can't seem to find a way around it. I have an application with a header, a few routes that require authorization, and a few routes that does not require authorization. The header contains a sign-in button to sign in.

As I understand it, having routes that does not require authorization is accomplished by defining those routes before the routes that require authorization, as such:
``` tsx
// Unauthorized routes
<Route path="/" exact component={Dashboard} />

// Authorized routes
<AuthProvider {...oidcConfig}>
  <Route path="/admin" component={Admin} />
</AuthProvider>
```

However, both of these components should use the same `<Header />`-component, where the header component has a button to sign in. Signing in is done through the `useAuth`-hook, but the `useAuth`-hook can only be used within the `AuthProvider`? This makes it impossible to use the header on the dashboard. Is there something that I've misunderstood?

**Comment by pseudoramble** [comment]
I'm not exactly sure if this is what you need, but here's what I would try:

Put `<AuthProvider {...oidcConfg}>` near the root of your React tree or router. Then in your `oidcConfig` object, set `autoSignIn: false`. You then control sign-in manually using the button in the header you're creating. That way, `oidc-react` still gets all the info it needs, but does not attempt to sign the user in right away when it doesn't detect a user.

**Comment by eTallang** [comment]
Thank you for the reply! We went for your approach :)

**Comment by pseudoramble** [comment]
I actually setup something semi-related in an app like this. So I thought I'd share a skeleton of the component I've been using in case others need inspiration:

```
import { useEffect } from "react";
import { useAuth } from "oidc-react";

interface AuthenticatedProps {
  children: any;
  LoadingComp?: any;
}

const DefaultLoadingComp = () => <div>Loading, Please Wait</div>;

const Authenticated = ({ children, LoadingComp = DefaultLoadingComp }: AuthenticatedProps) => {
  const auth = useAuth();

  useEffect(() => {
    const authenticate = async () => {
      if (!auth?.isLoading && !auth?.userData) {
        try {
          await auth.userManager?.signinSilent();
        } catch (e) {
          if (e.error === 'login_required') {
            await auth.signIn();
          }
        }
      }
    };

    authenticate();
  }, [auth, auth?.isLoading, auth?.userData, auth?.userManager]);

  if (auth.isLoading) {
    return <LoadingComp />;
  } else if (!auth?.isLoading && auth?.userData) {
    return children;
  }

  return null;
};

export default Authenticated;
```

The way I use this then is:

1. Wrap the whole app with `AuthProvider` but explicitly set `autoSignIn` to false.
2. Find the components requiring authentication and wrap them with this `Authenticated` component.
3. This will then make sure that protected components require sign-in, but not protected ones don't take action (unless of course you do what @eTallang did and call `auth.signIn()` later on).

Again, this is more just an idea on where to get started. Something more like this baked into `oidc-react` might be nice, but for now this should help.

**Comment by cobraz** [comment]
> Again, this is more just an idea on where to get started. Something more like this baked into `oidc-react` might be nice, but for now this should help.

Hey, thanks for that idea! We should definitely look into that!
