### ISSUE TITLE
onBeforeSignIn not invoked when calling signIn

### ISSUE THREAD

**Issue by pseudoramble** [bjerkio/oidc-react#705]
I noticed that when signIn is called directly, as opposed to say `autoSignIn` the `onBeforeSignIn` hook is not called. I think it's inconsistent to do it this way since it seems like the kind of thing that should be always called regardless of when or how sign in is occurring.

Looking back at old issues though, I did notice https://github.com/bjerkio/oidc-react/issues/36 and https://github.com/bjerkio/oidc-react/issues/447 which seem to point to using oidc-client and the back end to handle this kind of work. I wasn't aware of this as an option until I came across this issue.

So two ideas I had for this:

1. Call `onBeforeSignIn` whenever the `signIn` function is called.
2. Consider deprecating `onBeforeSignIn` for future releases and encourage people to use these other options.

I'm partial to the first option because it's less work for me 😆 but I figured I'd at least write this down as a potential issue.

**Comment by MaelthiS** [comment]
+1

**Comment by MaelthiS** [comment]
@cobraz any news on this ?

**Comment by jamesdh** [comment]
This is still an issue, and I should be able to resolve it as part of some additional cleanup.

**Comment by simenandre** [comment]
Closing this as stale. Please open a new issue or let me know you still have this issue in a comment 👍
