### ISSUE TITLE
onSignIn() callback fires multiple times

### ISSUE THREAD

**Issue by mrszympek** [bjerkio/oidc-react#717]
Hi! Thanks for creating this lib! I've got some problem with the signIn. Here's my code
`    onSignIn: (user: User || null) => {
      console.log('user', user)
      sessionStorage.setItem('access_token', user.access_token);
      history.push('/')
    }`

Here's the result
![Screenshot 2021-09-05 at 15 03 04](https://user-images.githubusercontent.com/13149889/132127888-62f0d3a9-5384-4261-935b-f108f5fc4958.png)

As you can see the onSignIn callback, fires multiple times. What Am I doing wrong? 

Is there something wrong with getUser() in `AuthContext.tsx` ?

**Comment by cobraz** [comment]
Hello!

Thanks for posting this. Would you mind creating a simple repro?

**Comment by benjamin-musil** [comment]
Also having this same issue, thought this is almost a year later so probably not helpful now. HMR of the SPA might be triggering this, while using vite I found that the normal run dev script was causing multiple callbacks. If you do a build then serve those files you should see the later `undefined`'s go away.

**Comment by cobraz** [comment]
This issue seems to have gone stale.

I'm closing this now, but feel free to open a new issue or let me know if this should be reopened :)
