### ISSUE TITLE
renew of access_token when token expired

### ISSUE THREAD

**Issue by tsaint31** [bjerkio/oidc-react#725]
I succeed to connect with AuthProvider and i retrieve the access_token (and a refresh_token) in the session storage.

Now i would like to trigger automatically a silent renew when i received a 401 "Jwt is expired".

I catch the 401 error and try to launch
      new UserManager(configAuth).startSilentRenew();
but nothing happen.

Is there a configuration that allow that with oidc-react?

**Comment by pseudoramble** [comment]
Does `automaticSignInRenew` feature work for you? I think that fits the bill.

https://github.com/bjerkio/oidc-react/blob/master/docs/interfaces/authcontextinterface.authproviderprops.md#automaticsilentrenew
