### ISSUE TITLE
Using PKCE flow

### ISSUE THREAD

**Issue by matwii** [bjerkio/oidc-react#753]
Hey is it possible to set up PKCE flow with this package?
Anyone have any examples on how to implement it with the hook?

https://developers.onelogin.com/openid-connect/guides/auth-flow-pkce

**Comment by cobraz** [comment]
Most of my own implementations use PKCE. I can check if there are some examples I can share :)

**Comment by matwii** [comment]
@cobraz I don't want to rush you, but did you find any react example with PKCE flow? 😃

**Comment by raman-nbg** [comment]
I'm also interested in how to implement Authorization Code Flow with PKCE.

**Comment by cobraz** [comment]
👋 

I intended to create a sample repository (or update the ones I had) but never got around to it. It should be enough to change the `responseType` argument to `code`, and you're off to the races.

Maybe you can try it and share your findings? :)

**Comment by Zysberg** [comment]
Hey, newbie here, confused why just setting the response type to `code` enables PKCE
