### ISSUE TITLE
Hook does not work

### ISSUE THREAD

**Issue by boldt** [bjerkio/oidc-react#778]
The [hook descibed in the guides](https://github.com/bjerkio/oidc-react/blob/main/guides/HOOKS.md) does not work (any more?) as it is documented. I called:

```
const auth = useAuth();
```

This is the result of `auth`, and as you can see, there is no `profile`, which is used in the hook-guide:

![grafik](https://user-images.githubusercontent.com/750793/148218698-4e2db77a-692b-44d7-9deb-a0f4a31d6fb5.png)

In the `onSignIn` after the login I do see the `profile`.

**Comment by mr-perseus** [comment]
Did you set loadUserInfo to true?

```jsx
<AuthProvider /* (Other options) */ loadUserInfo>
    <App />
</AuthProvider>
```

**Comment by cobraz** [comment]
This issue seems to have gone stale.

I'm closing this now, but feel free to open a new issue or let me know if this should be reopened :)
