### ISSUE TITLE
release-please action failing

### ISSUE THREAD

**Issue by braaar** [bjerkio/oidc-react#785]
[A release was requested](https://github.com/bjerkio/oidc-react/pull/764#issuecomment-1018457789) following a recent fix PR.

And it turns out release please is not working! 

I first figured https://github.com/bjerkio/oidc-react/commit/0df3cab516a8fee90ec4e09c8589940a536c54d1 could have fixed the issue. 

It did not. See [this action run](https://github.com/bjerkio/oidc-react/runs/4896712825?check_suite_focus=true) (triggered by an empty commit)

```shell
✖ Error when creating branch
Error: release-please failed: Error creating Pull Request: Not Found
```

**Comment by braaar** [comment]
@cobraz, have you had this happen before?

**Comment by cobraz** [comment]
Should be fixed now :)
