### ISSUE TITLE
Distinguish between "not logged in" and "OIDC service not available"

### ISSUE THREAD

**Issue by boldt** [bjerkio/oidc-react#787]
Is there any was to distinguish between "not logged in" and "OIDC service not available"?
When the OIDC service is not available, I see the following error in the console:

![grafik](https://user-images.githubusercontent.com/750793/150806675-91ce061f-31cb-475c-ab67-bb335f7bab9e.png)

The user is not forwarded to the login page, and with the `useAuth`-hook, I can only determine whether a user is logged in or not. 
Is there any way to show an error, that the login service is not available?

**Comment by cobraz** [comment]
Thank you so much for posting this!

Sure enough, this is something we probably need to improve on. I'm not sure what errors `oidc-client` (the underlying package) throws in these cases, but there should, sure enough, be better than this. Have you tried an error boundary, just to catch the ones you have? I would love to hear about your findings. (Hadn't had time to check on this myself)

**Comment by cobraz** [comment]
Hey, it's been a while since we saw an update on this issue. @boldt, would you be interested in looking into ways we can improve on this in this library?

**Comment by simenandre** [comment]
Closing this as stale, let me know if you want to work on it, and I'll open it again! 👍
