### ISSUE TITLE
ReactDOM.render is no longer supported in React 18. Use createRoot instead.

### ISSUE THREAD

**Issue by simenandre** [bjerkio/oidc-react#862]
Tests are warning us that we are using a deprecated feature. It can be seen in this build:
https://github.com/bjerkio/oidc-react/runs/7359386639?check_suite_focus=true

The full warning is this:
```
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
```

Seems like we have a few references to this in our tests, so if anyone wants to open a pull request fixing that it would be awesome!

**Comment by Ebukachuqz** [comment]
> so if anyone wants to open a pull request fixing that it would be awesome!
I would love to do that. 
However , I can't seem to find the file where `ReactDOM.render` is called. Can you tell me out please.

**Comment by Ebukachuqz** [comment]
> so if anyone wants to open a pull request fixing that it would be awesome!

I would love to do that.
However , I can't seem to find the file where `ReactDOM.render` is called. Can you tell me out please.

**Comment by cobraz** [comment]
If you open the step (collapsible) named `Run yarn test`, there should be some more details there.

PS: Currently on my mobile phone, so I couldn't verify 😅
