### ISSUE TITLE
GitHub OAuth compatibility

### ISSUE THREAD

**Issue by AndresJulia** [bjerkio/oidc-react#875]
Is it possible to use Githb OAuth feature for with this?
Getting the following:

```
GET https://github.com/login/oauth/authorize/.well-known/openid-configuration net::ERR_FAILED 404
```

**Comment by cobraz** [comment]
I haven't used OIDC with Github before, are you sure it support OIDC and not just OAuth?

**Comment by braaar** [comment]
Wikipedia says No OIDC for github:
https://en.wikipedia.org/wiki/List_of_OAuth_providers
