### ISSUE TITLE
example

### ISSUE THREAD

**Issue by arezookheirabedi** [bjerkio/oidc-react#886]
hi. I clone example-oidc-react but I couldn't find out how you request to get a token. I'm new in auth from the front .please send me an example for request and getting token and refresh token.thanx alot

**Comment by cobraz** [comment]
Hello 👋 

This should be covered in `example-oidc-react`. Can you explain what you are looking for? :)

**Comment by cobraz** [comment]
Hey! We haven't heard back on this, but I would love to see more examples added to this repository.

If you are up for it, we would love to see a PR on this!

Closing this for now, but feel free to open a new issue!
