### ISSUE TITLE
Redirect to original URL after signin (deep linking)

### ISSUE THREAD

**Issue by elliotgonzalez-lk** [bjerkio/oidc-react#887]
Hello!  I am migrating from a now deprecated oidc client library to this one, and everything has gone smoothly.  However, I cannot figure out how to redirect the user to the original URL after signin.  I apologize if I am missing something terribly obvious, but I cannot figure this out.

Logged out user pastes `http://localhost:3000/blog/1` into the browser URL bar  -> They are redirected to the IDP signin page -> Enter username and password -> authenticated -> redirected to the `/` route instead of `http://localhost:3000/blog/1`

- I see the `state` param key appended to the URL during the callback. 
- The `state` key on `userData` is always undefined.  Any attempt to update this value does not work due to it being readonly.  
- Trying to run `window.history.replaceState()` in the `onSignin` callback does nothing.

Does the library do anything with that `state` param?  Is there any way to implement deep linking?  Would you be able to point me to any examples of this working?  I would greatly appreciate it.  Thanks.

**Comment by horizondave** [comment]
Never used it myself, but I was looking to see if support for this functionality was provided too.
I think it's a case of DIY using the onBeforeSignin and onSignin hooks.
https://github.com/bjerkio/oidc-react/blob/main/docs/interfaces/authcontextinterface.authproviderprops.md#onbeforesignin

**Comment by laurakutovaja** [comment]
@elliotgonzalez-lk any luck with this issue?

**Comment by forforfos** [comment]
Seems that @laurakutovaja fixed this! Maybe this issue should be closed?

**Comment by braaar** [comment]
fixed by #910

**Comment by AlexanderKositsyn** [comment]
When will it be released? I need this fix
