### ISSUE TITLE
log out dosent work for me

### ISSUE THREAD

**Issue by arezookheirabedi** [bjerkio/oidc-react#889]

**Comment by arezookheirabedi** [comment]
i can sign in and get token but when i cal logout it doesn't work

**Comment by kodeschooler** [comment]
what does ```it doesn't work ``` mean? Do you have a redirect uri defined in the settings? Is it being called ? Do you have a route for it?

**Comment by cobraz** [comment]
This issue seems to have gone stale. I'm closing this now, but feel free to open a new issue or let me know if this should be reopened :)

**Comment by jamesdh** [comment]
Closing due to lack of information.
