### ISSUE TITLE
Change the acr_values dynamically to pass a new tenant

### ISSUE THREAD

**Issue by kodeschooler** [bjerkio/oidc-react#897]
I've been using this library with no issues, but I'm wondering how to change one of the read-only settings during the use of my app (ie, after the ```UserManager``` class is instantiated)? 

When an admin user selects a customer from a list, I want to change the acr_values to the tenant selected so subsequent tokens will contain that tenant id.

**Comment by kodeschooler** [comment]
??

**Comment by cobraz** [comment]
I'm unsure what you're trying to do here, but you can easily update the configuration values using some state setup.

**Comment by simenandre** [comment]
Closing this as stale. Please open a new issue or let me know you still have this issue in a comment 👍
