### ISSUE TITLE
Silent renew not working when in Strict Mode

### ISSUE THREAD

**Issue by Episodex** [bjerkio/oidc-react#907]
I had a problem, similar to https://github.com/bjerkio/oidc-react/issues/361 except the PR merged then didn't fix my problem. It turned out that `AuthContext` is being mounted twice when React is in Strict mode. This causes this line to run: `isMountedRef.current = false;` and nothing then sets it back to true. Which effectively disables updating user info: https://github.com/bjerkio/oidc-react/blob/d6958d1c71e84f02354e18a0db27a19b3ede3840/src/AuthContext.tsx#L138 .

I fixed it by setting `isMountedRef.current` to `true` on every mount:

```
useEffect(() => {
    isMountedRef.current = true; // <-- my change
    return () => {
      isMountedRef.current = false;
    };
  }, []);
```

I'm not sure if it's the right way, but it seems to solve the problem for me. Maybe it's worth adding to the repo.

**Comment by JapuDCret** [comment]
May be fixed by the workaround mentioned in #901
