### ISSUE TITLE
Cannot Populate UserData

### ISSUE THREAD

**Issue by Ed-Marcavage** [bjerkio/oidc-react#917]
I am implementing oidc-react in my typescript react app using the ChakraUI component Lib. I am trying to Auth with Azure AD, it successfully redirects the user back to the web page (hosted locally) after authenticating. However, I cannot get UserData to populate (see screen shot). I have pasted snippets of my implementation below. The goal is to gather user info from the SAML assertion with AzureAD, which I believe should be stored in UserDate? 

/src/index.tsx
```javascript
root.render(
  <React.StrictMode>
    <AuthProvider
    authority="https://login.microsoftonline.com/____________________________"
    clientId="______________________"
    redirectUri="http://localhost:3002"
    loadUserInfo
    >
    <ColorModeScript />
    <ChakraProvider theme={theme}>
      <App />
    </ChakraProvider>
    </AuthProvider>
  </React.StrictMode>
);
```

simply return useAuth to the console for testing/seeing the UserData values
/src/App.tsx
```javascript
export const App = () => {
  const auth = useAuth();
  console.log(auth)
....
```
![Screen Shot 2022-10-20 at 11 33 31 AM](https://user-images.githubusercontent.com/61299527/196993165-2fb5ba9f-eb41-4d5f-910a-21538524989e.png)

**Comment by GNUGradyn** [comment]
any update on this? I am having the same issue. Identity provider redirects back to app, but isLoading is true and userData is null

**Comment by hubertsuwala** [comment]
hi, could you tell me what this status mean "kind/bug"? Anyone did resolve this bug, I have the same on firefox, chrome, and safari on Macbook Pro M1, on windows everything is fine

**Comment by MaelthiS** [comment]
I have the bug too, please provide a solution

**Comment by simenandre** [comment]
Closing this as stale. Please open a new issue or let me know you still have this issue in a comment 👍
