### ISSUE TITLE
Add a check that  `oidc.{state}` exists in localStorage.

### ISSUE THREAD

**Issue by AlexanderKositsyn** [bjerkio/oidc-react#922]
Redirect to `localhost/?state=123&code=...` with no `oidc.123` in localStorage couses error `Error: No matching state found in storage`
https://github.com/bjerkio/oidc-react/blob/f20f92854ffef3f8e6c9b5c8a2e11ed58da4731e/src/AuthContext.tsx#L115

**Comment by flcarre** [comment]
Got same issue, +1

**Comment by shtbik** [comment]
+1

**Comment by tdipadova3rd** [comment]
+1

**Comment by jamesdh** [comment]
This issue feels like a show stopper. We just switched from [react-keycloak](https://github.com/react-keycloak/react-keycloak) to oidc-react and this is the first big issue we're repeatedly encountering.  It also completely demolishes the URL so simply doing a reload does not fix it.
