### ISSUE TITLE
Add compatibility with Ionic React 

### ISSUE THREAD

**Issue by TalaatHarb** [bjerkio/oidc-react#980]
This is a feature request, of adding Basic compatibility with Ionic React,
Currently it almost works, as it does the redirect for the authority and receives the token and saves it storage but it keeps looping and refreshing the page after that which is a shame.

Steps to reproduce:
- build a new Ionic React app by using the the ionic wizard 'ionic start'
- install oidc-react
- add oidc config as normal react project with a valid authority and client id and redirect_uri = 'http://localhost:8100'
- start the application and observe looping behavior 'ionic serve'

**Comment by jamesdh** [comment]
@TalaatHarb this may not be related to Ionic specifically. This might be a bug I introduced last Friday. 

Are you using `autoSignIn` or do you have it disabled by chance?
